[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Add core functionality

[[patches]]
[patches.copy]
target = "main.lua"
position = "append"
sources = [
    "cartomancer.lua",
    "core/view-deck.lua",
    "core/flames.lua",
    "core/shaders.lua",
#    "core/hidden-jokers.lua",
]

# Fix UIElement.config.chosen being overriden if choice=true is set
# UIElement:click()
[[patches]]
[patches.pattern]
target = "engine/ui.lua"
match_indent = true
position = "after"
pattern = "if self.config.choice then"
payload = "    local chosen_temp = self.config.chosen"

[[patches]]
[patches.pattern]
target = "engine/ui.lua"
match_indent = true
position = "at"
pattern = "self.config.chosen = true"
payload = "self.config.chosen = chosen_temp or true"