[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.module]
source = "nativefs/nativefs.lua"
before = "main.lua"
name = "nativefs"

# Add settings

[[patches]]
[patches.copy]
target = "main.lua"
position = "append"
sources = [
    "cartomancer.lua",
    "core/view-deck.lua",
    "core/flames.lua",
    "core/shaders.lua",
    "core/hidden-jokers.lua",
]
