[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

# Add settings

[[patches]]
[patches.copy]
target = "main.lua"
position = "append"
sources = [
    "settings.lua",
    "core/view-deck-steamodded.lua",
    "core/view-deck.lua",
    "core/score-flames.lua",
    "core/shaders.lua",
    "core/hidden-jokers.lua",
]

