[manifest]
version = "1.0.0"
dump_lua = true
priority = -10

# Patches applied before steamodded.

[[patches]]
[patches.copy]
target = "main.lua"
position = "prepend"
sources = [
    "core/view-deck-steamodded.lua",
]
