[manifest]
version = "1.0.0"
dump_lua = true
priority = 69


#
# End of round money
#

# Hide off screen rows

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if config.name ~= 'bottom' then"
position = "at"
payload = '''
if config.name ~= 'bottom' then

    G.GAME.round_eval_rows = G.GAME.round_eval_rows + 1
    if G.GAME.round_eval_rows > 7 then
        return
    end
'''
match_indent = true

# Reset rows amount

[[patches]]
[patches.regex]
target = "functions/state_events.lua"
pattern = 'G\.FUNCS\.evaluate_round = function\(\)'
position = "at"
payload = '''
G.FUNCS.evaluate_round = function()
G.GAME.round_eval_rows = 0'''

# Add UI row with total rows hidden

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "add_round_eval_row({name = 'bottom', dollars = dollars})"
position = "before"
payload = '''
if G.GAME.round_eval_rows > 7 then
    local total_hidden = G.GAME.round_eval_rows - 7

G.E_MANAGER:add_event(Event({
    trigger = 'before',delay = 0.38,
    func = function()

        local hidden = {n=G.UIT.R, config={align = "cm", minw = G.round_eval.T.w - 0.51}, nodes={
            {n=G.UIT.O, config={object = DynaText({
                -- todo: localization mayhaps?
                string = {string.format('...and %s more', total_hidden)}, 
                colours = {G.C.MONEY}, shadow = true, float = false, 
                scale = 0.65,
                font = G.LANGUAGES['en-us'].font, pop_in = 0
            })}}
        }}
        G.round_eval:add_child(hidden,G.round_eval:get_UIE_by_ID('bonus_round_eval'))
        return true
    end
}))
    
end

'''
match_indent = true

